# -*- coding: utf-8 -*-
"""dolly-v2-3b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWyBLQvtV-DA_J4EDAXnPhMcB6FfM9Nf
"""

!pip install transformers
!pip install sentencepiece
!pip install accelerate

import torch
import os
from transformers import pipeline

dolly_pipeline = pipeline(model = "databricks/dolly-v2-3b",)

dolly_pipeline = pipeline(model = "databricks/dolly-v2-3b",
                          torch_dtype=torch.bfloat16,
                          trust_remote_code=True,
                          device_map="auto")

def get_completion(input):
  system = f"""
  You are an expert physicist.
  You are good at explaining physics concepts in simple words.
  Help as much as you can.
  """

  prompt = f"#### System : {system}\n#### User: \n{input}\n\n#### Response from Assistant:"
  print(prompt)
  dolly_response = dolly_pipeline(prompt, max_new_tokens=500)
  return dolly_response[0]["generated_text"]

prompt = "Explain the difference between nuclear fission and fusion."

print(get_completion(prompt))